services:
  db:
    image: postgres
    container_name: "postgres"
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql


  server:
    build:
      context: ./server
    container_name: "credit-flow-server"
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: http://localhost:3000
    container_name: "credit-flow-client"
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env

volumes:
  pgdata:
